CREATE TABLE `hris_employee` (
  `employee_Id` int NOT NULL AUTO_INCREMENT,
  `employee_first_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_last_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_gender` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_personal_email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_wso2_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employee_contact_number` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_employment_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_career_function` int NOT NULL,
  `employee_business_unit` int NOT NULL,
  `employee_department` int NOT NULL,
  `employee_team` int NOT NULL,
  `employee_sub_team` int DEFAULT NULL,
  `employee_job_band` int NOT NULL,
  `employee_date_of_join` date NOT NULL,
  `employee_probation_end_date` date DEFAULT NULL,
  `employee_agreement_end_date` date DEFAULT NULL,
  `employee_company` int NOT NULL,
  `employee_office` int NOT NULL,
  `employee_work_location` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_reports_to` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employee_manager_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `employee_compensation` json DEFAULT NULL,
  `employee_offer_documents` json DEFAULT NULL,
  `employee_additional_comments` blob,
  `employee_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_created_by` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee_created_on` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `employee__updated_by` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `employee__updated_on` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`employee_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
